# Generated by Django 5.1.7 on 2025-03-26 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام لیست توزیع')),
                ('note', models.TextField(default='', verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('max_members', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_code', models.IntegerField(verbose_name='شماره پرونده')),
                ('need_level', models.IntegerField(choices=[(1, 'متوسط'), (2, 'شدید'), (3, 'خیلی شدید')], default=1, verbose_name='سطح نیاز')),
                ('family_type', models.IntegerField(choices=[(1, 'یتیم'), (2, 'زندانی'), (3, 'مطلقه'), (4, 'رها شده'), (5, 'بیمار'), (6, 'فقیر')], default=1, verbose_name='نوع نیازمندی')),
                ('address', models.CharField(max_length=255, verbose_name='آدرس')),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس')),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='کدپستی')),
                ('is_active', models.BooleanField(choices=[(True, 'تحت حمایت'), (False, 'عدم حمایت')], default=True, verbose_name='تحت پوشش')),
                ('distlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mohsenin.dist', verbose_name='لیست توزیع')),
            ],
        ),
        migrations.CreateModel(
            name='InmateRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mohsenin.family')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalAid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_needs', models.TextField()),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mohsenin.family')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('observation_date', models.DateField()),
                ('notes', models.TextField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mohsenin.family')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('father_name', models.CharField(max_length=50, verbose_name='نام پدر')),
                ('national_id', models.CharField(max_length=10, verbose_name='شماره ملی')),
                ('birth_date', models.DateField(verbose_name='تاریخ تولد')),
                ('is_orphan', models.BooleanField(choices=[(True, 'بله'), (False, 'خیر')], verbose_name='یتیم')),
                ('is_active', models.BooleanField(choices=[(True, 'تحت حمایت'), (False, 'عدم حمایت')], default=True, verbose_name='تحت پوشش')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='Mohsenin.family', verbose_name='خانواده')),
            ],
        ),
        migrations.CreateModel(
            name='PackageDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distribution_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mohsenin.family')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Mohsenin.package')),
                ('members', models.ManyToManyField(related_name='packages', to='Mohsenin.person')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='guardian',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardianship', to='Mohsenin.person', verbose_name='سرپرست خانوار'),
        ),
    ]
