# Generated by Django 5.1.11 on 2025-07-07 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mohsenin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('is_active', models.BooleanField(choices=[(True, 'فعال'), (False, 'غیرفعال')], default=True, verbose_name='فعال')),
                ('supports_orphans_only', models.BooleanField(choices=[(True, 'بله'), (False, 'خیر')], default=True, verbose_name='فقط حمایت از یتیمان')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='onePerFamily',
            field=models.BooleanField(choices=[(True, 'بله'), (False, 'خیر')], default=False, verbose_name='هرخانواده یک بسته'),
        ),
        migrations.AlterField(
            model_name='family',
            name='distlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families', to='Mohsenin.dist', verbose_name='لیست توزیع'),
        ),
        migrations.AlterField(
            model_name='package',
            name='cost',
            field=models.PositiveIntegerField(verbose_name='ارزش ریالی هر بسته'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='package',
            name='max_members',
            field=models.PositiveIntegerField(verbose_name='ظرفیت بسته'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام بسته'),
        ),
        migrations.AlterField(
            model_name='family',
            name='family_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Mohsenin.family_type', verbose_name='نوع نیازمندی'),
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_date', models.DateField(auto_now_add=True, verbose_name='تاریخ حمایت')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ حمایت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportings', to='Mohsenin.person')),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='Mohsenin.supporter')),
            ],
        ),
    ]
