# Generated by Django 5.1.7 on 2025-04-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mohsenin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='cost',
            field=models.PositiveIntegerField(verbose_name='ارزش ریالی هر بسته'),
        ),
        migrations.AlterField(
            model_name='package',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='package',
            name='max_members',
            field=models.PositiveIntegerField(verbose_name='ظرفیت بسته'),
        ),
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام بسته'),
        ),
    ]
