# Generated by Django 5.1.11 on 2025-07-07 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mohsenin', '0002_family_type_supporter_package_oneperfamily_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Mohsenin.family_type', verbose_name='نوع نیازمندی'),
        ),
    ]
