# Generated by Django 5.1.7 on 2025-04-02 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mohsenin', '0002_alter_package_cost_alter_package_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('supports_orphans_only', models.BooleanField(choices=[(True, 'بله'), (False, 'خیر')], default=True, verbose_name='فقط حمایت از یتیمان')),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_date', models.DateField(auto_now_add=True, verbose_name='تاریخ حمایت')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مبلغ حمایت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supportings', to='Mohsenin.person')),
                ('supporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='Mohsenin.supporter')),
            ],
        ),
    ]
