# Generated by Django 5.1.8 on 2025-04-21 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mohsenin', '0003_supporter_support'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supporter',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='supporter',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='family',
            name='distlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families', to='Mohsenin.dist', verbose_name='لیست توزیع'),
        ),
    ]
