# Generated by Django 5.1.11 on 2025-07-07 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mohsenin', '0003_alter_family_family_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='family_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mohsenin.family_type', verbose_name='نوع نیازمندی'),
        ),
    ]
