# Generated by Django 5.1.8 on 2025-05-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mohsenin', '0004_rename_first_name_supporter_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='onePerFamily',
            field=models.BooleanField(choices=[(True, 'بله'), (False, 'خیر')], default=False, verbose_name='هرخانواده یک بسته'),
        ),
    ]
