# Generated by Django 5.2.4 on 2025-07-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mohsenin', '0004_alter_family_family_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='تحت پوشش'),
        ),
    ]
