# Generated by Django 5.2.4 on 2025-07-11 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mohsenin', '0005_alter_family_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='distlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='families', to='Mohsenin.dist', verbose_name='لیست توزیع'),
        ),
    ]
