# Generated by Django 5.2.4 on 2025-07-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mohsenin', '0006_alter_family_distlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='مبلغ حمایت'),
        ),
    ]
